<?php

namespace Database\Seeders;

use App\Models\Trip;
use Illuminate\Database\Seeder;

class TripSeeder extends Seeder
{
    public function run(): void
    {
        $trips = [
            [
                'title'           => ['ar' => 'غردقة الساحرة',                    'en' => 'Magical Hurghada'],
                'country'         => ['ar' => 'مصر',                              'en' => 'Egypt'],
                'desc'            => ['ar' => 'استمتع بشواطئ الغردقة الرائعة وغوص في أعماق البحر الأحمر، رحلة لا تُنسى بأسعار مناسبة.', 'en' => 'Enjoy the stunning beaches of Hurghada and dive into the Red Sea depths — an unforgettable trip at affordable prices.'],
                'highlights'      => ['ar' => ['غوص وسنوركل','رياضات مائية','رحلة صحراوية','كورنيش الغردقة'], 'en' => ['Diving & Snorkeling','Water Sports','Desert Safari','Hurghada Corniche']],
                'price' => 350, 'currency' => '$', 'duration' => 5,
                'category' => 'beach', 'climate' => 'beach', 'travel_type' => ['family','couple','friends'],
                'budget_tier' => 'low', 'color_from' => '#0099CC', 'color_to' => '#FF6633',
                'is_egyptian' => true, 'spots_total' => 20, 'spots_left' => 5,
                'departure_dates' => ['2026-04-20','2026-05-10','2026-06-05','2026-07-01'],
                'is_active' => true, 'sort_order' => 1,
            ],
            [
                'title'           => ['ar' => 'شرم الشيخ الأسطوري',               'en' => 'Legendary Sharm El-Sheikh'],
                'country'         => ['ar' => 'مصر',                              'en' => 'Egypt'],
                'desc'            => ['ar' => 'جنة الشعاب المرجانية وأجمل شواطئ مصر في رحلة مثيرة بين الجبال والبحر.', 'en' => "Paradise of coral reefs and Egypt's most beautiful beaches in an exciting journey between mountains and sea."],
                'highlights'      => ['ar' => ['نعمة باي','جزيرة تيران','سوق شرم','رحلة الصحراء'], 'en' => ['Naama Bay','Tiran Island','Sharm Market','Desert Trip']],
                'price' => 420, 'currency' => '$', 'duration' => 6,
                'category' => 'beach', 'climate' => 'beach', 'travel_type' => ['couple','family','friends'],
                'budget_tier' => 'low', 'color_from' => '#00B4D8', 'color_to' => '#F77F00',
                'is_egyptian' => true, 'spots_total' => 18, 'spots_left' => 3,
                'departure_dates' => ['2026-04-25','2026-05-15','2026-06-10'],
                'is_active' => true, 'sort_order' => 2,
            ],
            [
                'title'           => ['ar' => 'الأقصر وأسوان — أرض الفراعنة',   'en' => 'Luxor & Aswan — Land of Pharaohs'],
                'country'         => ['ar' => 'مصر',                              'en' => 'Egypt'],
                'desc'            => ['ar' => 'رحلة في أعماق التاريخ المصري القديم بين معابد الكرنك وأبو سمبل والمتحف الفرعوني.', 'en' => 'A journey into ancient Egyptian history between Karnak temples, Abu Simbel, and the Pharaonic museum.'],
                'highlights'      => ['ar' => ['معبد الكرنك','أبو سمبل','وادي الملوك','رحلة النيل'], 'en' => ['Karnak Temple','Abu Simbel','Valley of Kings','Nile Cruise']],
                'price' => 500, 'currency' => '$', 'duration' => 7,
                'category' => 'culture', 'climate' => 'desert', 'travel_type' => ['family','couple','solo'],
                'budget_tier' => 'medium', 'color_from' => '#8B4513', 'color_to' => '#C5A028',
                'is_egyptian' => true, 'spots_total' => 15, 'spots_left' => 9,
                'departure_dates' => ['2026-05-01','2026-05-22','2026-07-03'],
                'is_active' => true, 'sort_order' => 3,
            ],
            [
                'title'           => ['ar' => 'باريس — مدينة الأنوار',            'en' => 'Paris — City of Lights'],
                'country'         => ['ar' => 'فرنسا',                            'en' => 'France'],
                'desc'            => ['ar' => 'استكشف عاصمة الفنون والموضة، من برج إيفل إلى متحف اللوفر في رحلة رومانسية لا مثيل لها.', 'en' => 'Explore the capital of arts and fashion, from the Eiffel Tower to the Louvre in an unparalleled romantic journey.'],
                'highlights'      => ['ar' => ['برج إيفل','متحف اللوفر','الشانزليزيه','قصر فرساي'], 'en' => ['Eiffel Tower','Louvre Museum','Champs-Élysées','Palace of Versailles']],
                'price' => 1500, 'currency' => '$', 'duration' => 7,
                'category' => 'culture', 'climate' => 'city', 'travel_type' => ['couple','solo'],
                'budget_tier' => 'high', 'color_from' => '#003087', 'color_to' => '#ED2939',
                'is_egyptian' => false, 'spots_total' => 20, 'spots_left' => 12,
                'departure_dates' => ['2026-05-05','2026-06-12','2026-07-10'],
                'is_active' => true, 'sort_order' => 4,
            ],
            [
                'title'           => ['ar' => 'روما — العاصمة الأبدية',           'en' => 'Rome — The Eternal City'],
                'country'         => ['ar' => 'إيطاليا',                          'en' => 'Italy'],
                'desc'            => ['ar' => 'تجول في شوارع التاريخ بين الكولوسيوم والفاتيكان وينابيع تريفي في مدينة خالدة.', 'en' => 'Walk through streets of history between the Colosseum, Vatican, and Trevi Fountain in an eternal city.'],
                'highlights'      => ['ar' => ['الكولوسيوم','الفاتيكان','نافورة تريفي','البانثيون'], 'en' => ['Colosseum','Vatican City','Trevi Fountain','Pantheon']],
                'price' => 1300, 'currency' => '$', 'duration' => 6,
                'category' => 'culture', 'climate' => 'city', 'travel_type' => ['couple','family','solo'],
                'budget_tier' => 'high', 'color_from' => '#009246', 'color_to' => '#CE2B37',
                'is_egyptian' => false, 'spots_total' => 16, 'spots_left' => 7,
                'departure_dates' => ['2026-04-28','2026-06-01','2026-07-18'],
                'is_active' => true, 'sort_order' => 5,
            ],
            [
                'title'           => ['ar' => 'برشلونة — مدينة الفن',             'en' => 'Barcelona — City of Art'],
                'country'         => ['ar' => 'إسبانيا',                          'en' => 'Spain'],
                'desc'            => ['ar' => 'من معمار غاودي الفريد إلى شواطئ لا باركيتا المذهلة، برشلونة تجمع الفن والمتعة معاً.', 'en' => "From Gaudí's unique architecture to the stunning beaches of La Barceloneta, Barcelona combines art and fun."],
                'highlights'      => ['ar' => ['الساغرادا فاميليا','لاس رامبلاس','شاطئ برشلونة','الحي القوطي'], 'en' => ['Sagrada Família','Las Ramblas','Barcelona Beach','Gothic Quarter']],
                'price' => 1200, 'currency' => '$', 'duration' => 6,
                'category' => 'adventure', 'climate' => 'beach', 'travel_type' => ['friends','couple','solo'],
                'budget_tier' => 'high', 'color_from' => '#AA151B', 'color_to' => '#F1BF00',
                'is_egyptian' => false, 'spots_total' => 20, 'spots_left' => 14,
                'departure_dates' => ['2026-05-08','2026-06-20','2026-08-01'],
                'is_active' => true, 'sort_order' => 6,
            ],
            [
                'title'           => ['ar' => 'دبي — مدينة المستقبل',             'en' => 'Dubai — City of the Future'],
                'country'         => ['ar' => 'الإمارات',                         'en' => 'UAE'],
                'desc'            => ['ar' => 'تسوق في أفخم المراكز التجارية وتزلج على الثلج بينما الصحراء تمتد خارج النافذة.', 'en' => 'Shop in the most luxurious malls and ski on snow while the desert stretches outside the window.'],
                'highlights'      => ['ar' => ['برج خليفة','دبي مول','ميناء جميرا','رحلة الصحراء'], 'en' => ['Burj Khalifa','Dubai Mall','Jumeirah Port','Desert Safari']],
                'price' => 900, 'currency' => '$', 'duration' => 5,
                'category' => 'adventure', 'climate' => 'desert', 'travel_type' => ['family','couple','friends'],
                'budget_tier' => 'high', 'color_from' => '#00732F', 'color_to' => '#C0392B',
                'is_egyptian' => false, 'spots_total' => 25, 'spots_left' => 2,
                'departure_dates' => ['2026-04-22','2026-05-18','2026-06-25'],
                'is_active' => true, 'sort_order' => 7,
            ],
            [
                'title'           => ['ar' => 'إسطنبول — جسر الحضارات',           'en' => 'Istanbul — Bridge of Civilizations'],
                'country'         => ['ar' => 'تركيا',                            'en' => 'Turkey'],
                'desc'            => ['ar' => 'مدينة تجمع بين شرق وغرب، بين آيا صوفيا والبسفور والبازارات الشرقية العريقة.', 'en' => 'A city that brings together East and West, between Hagia Sophia, the Bosphorus, and ancient Eastern bazaars.'],
                'highlights'      => ['ar' => ['آيا صوفيا','القصر الكبير','البازار المسقوف','جسر البسفور'], 'en' => ['Hagia Sophia','Topkapi Palace','Grand Bazaar','Bosphorus Bridge']],
                'price' => 700, 'currency' => '$', 'duration' => 6,
                'category' => 'culture', 'climate' => 'city', 'travel_type' => ['family','couple','friends','solo'],
                'budget_tier' => 'medium', 'color_from' => '#E30A17', 'color_to' => '#2E4053',
                'is_egyptian' => false, 'spots_total' => 22, 'spots_left' => 10,
                'departure_dates' => ['2026-05-03','2026-05-28','2026-07-05'],
                'is_active' => true, 'sort_order' => 8,
            ],
            [
                'title'           => ['ar' => 'بالي — جنة الأرض',                 'en' => 'Bali — Heaven on Earth'],
                'country'         => ['ar' => 'إندونيسيا',                        'en' => 'Indonesia'],
                'desc'            => ['ar' => 'جزيرة الآلهة ذات المعابد والشلالات والشواطئ البركانية الخلابة وثقافة فريدة من نوعها.', 'en' => 'Island of the gods with temples, waterfalls, volcanic beaches, and a unique culture like no other.'],
                'highlights'      => ['ar' => ['معبد أولوواتو','تراسات أوبود','شاطئ كوتا','كانيون أيانغ'], 'en' => ['Uluwatu Temple','Ubud Terraces','Kuta Beach','Ayung Canyon']],
                'price' => 800, 'currency' => '$', 'duration' => 10,
                'category' => 'beach', 'climate' => 'beach', 'travel_type' => ['couple','friends','solo'],
                'budget_tier' => 'medium', 'color_from' => '#FF6B35', 'color_to' => '#1A936F',
                'is_egyptian' => false, 'spots_total' => 18, 'spots_left' => 6,
                'departure_dates' => ['2026-05-12','2026-06-09','2026-08-11'],
                'is_active' => true, 'sort_order' => 9,
            ],
            [
                'title'           => ['ar' => 'نيويورك — المدينة التي لا تنام',  'en' => 'New York — The City That Never Sleeps'],
                'country'         => ['ar' => 'أمريكا',                           'en' => 'USA'],
                'desc'            => ['ar' => 'تجربة المدينة الأكثر إثارة في العالم، من تايمز سكوير إلى سنترال بارك والمتحف الأمريكي.', 'en' => 'Experience the most exciting city in the world, from Times Square to Central Park and the American Museum.'],
                'highlights'      => ['ar' => ['تايمز سكوير','سنترال بارك','تمثال الحرية','برودواي'], 'en' => ['Times Square','Central Park','Statue of Liberty','Broadway']],
                'price' => 2500, 'currency' => '$', 'duration' => 8,
                'category' => 'adventure', 'climate' => 'city', 'travel_type' => ['friends','couple','solo'],
                'budget_tier' => 'luxury', 'color_from' => '#3C3B6E', 'color_to' => '#B22234',
                'is_egyptian' => false, 'spots_total' => 15, 'spots_left' => 8,
                'departure_dates' => ['2026-05-20','2026-07-01','2026-09-05'],
                'is_active' => true, 'sort_order' => 10,
            ],
            [
                'title'           => ['ar' => 'المالديف — المتعة الخالصة',        'en' => 'Maldives — Pure Paradise'],
                'country'         => ['ar' => 'المالديف',                         'en' => 'Maldives'],
                'desc'            => ['ar' => 'جزر المحيط الهندي الخيالية مع أكواخ فوق الماء وشعاب مرجانية بلورية وغروب شمس لا يوصف.', 'en' => 'Dreamy Indian Ocean islands with overwater bungalows, crystal coral reefs, and indescribable sunsets.'],
                'highlights'      => ['ar' => ['كوخ فوق الماء','الغوص في المرجان','غروب المحيط','سبا خاص'], 'en' => ['Overwater Bungalow','Coral Diving','Ocean Sunset','Private Spa']],
                'price' => 3000, 'currency' => '$', 'duration' => 7,
                'category' => 'beach', 'climate' => 'beach', 'travel_type' => ['couple'],
                'budget_tier' => 'luxury', 'color_from' => '#006994', 'color_to' => '#00C9A7',
                'is_egyptian' => false, 'spots_total' => 10, 'spots_left' => 1,
                'departure_dates' => ['2026-05-01','2026-06-15','2026-10-03'],
                'is_active' => true, 'sort_order' => 11,
            ],
            [
                'title'           => ['ar' => 'طوكيو — عاصمة المستقبل',           'en' => 'Tokyo — Capital of the Future'],
                'country'         => ['ar' => 'اليابان',                          'en' => 'Japan'],
                'desc'            => ['ar' => 'مزيج مذهل بين التكنولوجيا الحديثة والتراث الياباني الأصيل في مدينة لا تشبه أي مكان آخر.', 'en' => 'An amazing blend of modern technology and authentic Japanese heritage in a city unlike anywhere else.'],
                'highlights'      => ['ar' => ['جبل فوجي','شينجوكو','معبد سنسوجي','حي أكيهابارا'], 'en' => ['Mount Fuji','Shinjuku','Senso-ji Temple','Akihabara District']],
                'price' => 2200, 'currency' => '$', 'duration' => 9,
                'category' => 'culture', 'climate' => 'city', 'travel_type' => ['solo','couple','friends'],
                'budget_tier' => 'luxury', 'color_from' => '#BC002D', 'color_to' => '#2C3E50',
                'is_egyptian' => false, 'spots_total' => 20, 'spots_left' => 11,
                'departure_dates' => ['2026-05-15','2026-07-22','2026-09-17'],
                'is_active' => true, 'sort_order' => 12,
            ],
            [
                'title'           => ['ar' => 'المغرب — مملكة الألوان',           'en' => 'Morocco — Kingdom of Colors'],
                'country'         => ['ar' => 'المغرب',                           'en' => 'Morocco'],
                'desc'            => ['ar' => 'من أزقة مراكش الوردية إلى صحراء الصحراء الكبرى وشاطئ أغادير المدهش، رحلة بألف لون.', 'en' => 'From the pink alleys of Marrakech to the Sahara Desert and stunning Agadir beach — a journey of a thousand colors.'],
                'highlights'      => ['ar' => ['جامع الفنا','الصحراء الكبرى','فاس القديمة','شاطئ أغادير'], 'en' => ['Jemaa el-Fna','Sahara Desert','Ancient Fez','Agadir Beach']],
                'price' => 600, 'currency' => '$', 'duration' => 7,
                'category' => 'adventure', 'climate' => 'desert', 'travel_type' => ['friends','family','solo'],
                'budget_tier' => 'medium', 'color_from' => '#C1272D', 'color_to' => '#006233',
                'is_egyptian' => false, 'spots_total' => 20, 'spots_left' => 15,
                'departure_dates' => ['2026-04-24','2026-05-22','2026-06-19'],
                'is_active' => true, 'sort_order' => 13,
            ],
            [
                'title'           => ['ar' => 'جزر اليونان — أجمل شواطئ أوروبا', 'en' => "Greek Islands — Europe's Most Beautiful Beaches"],
                'country'         => ['ar' => 'اليونان',                          'en' => 'Greece'],
                'desc'            => ['ar' => 'سانتوريني الحالمة وميكونوس الصاخبة وجزر الإيجه الخلابة في رحلة بحرية فريدة.', 'en' => 'Dreamy Santorini and vibrant Mykonos and stunning Aegean islands in a unique sea journey.'],
                'highlights'      => ['ar' => ['سانتوريني','ميكونوس','جزيرة كريت','أكروبوليس أثينا'], 'en' => ['Santorini','Mykonos','Crete Island','Athens Acropolis']],
                'price' => 1100, 'currency' => '$', 'duration' => 8,
                'category' => 'beach', 'climate' => 'beach', 'travel_type' => ['couple','friends'],
                'budget_tier' => 'high', 'color_from' => '#0D5EAF', 'color_to' => '#FFFFFF',
                'is_egyptian' => false, 'spots_total' => 16, 'spots_left' => 4,
                'departure_dates' => ['2026-05-07','2026-06-04','2026-07-02'],
                'is_active' => true, 'sort_order' => 14,
            ],
            [
                'title'           => ['ar' => 'البر السويسري — قلب الألب',        'en' => 'Switzerland — Heart of the Alps'],
                'country'         => ['ar' => 'سويسرا',                           'en' => 'Switzerland'],
                'desc'            => ['ar' => 'تزلج على جبال الألب وتجول في قرى الشوكولاتة وبحيرة جنيف الرائعة في قلب أوروبا.', 'en' => 'Ski in the Alps, stroll through chocolate villages, and visit stunning Lake Geneva in the heart of Europe.'],
                'highlights'      => ['ar' => ['جبل يونغفراو','زيرمات','بحيرة جنيف','إنترلاكن'], 'en' => ['Jungfrau Mountain','Zermatt','Lake Geneva','Interlaken']],
                'price' => 2800, 'currency' => '$', 'duration' => 8,
                'category' => 'adventure', 'climate' => 'mountain', 'travel_type' => ['family','couple'],
                'budget_tier' => 'luxury', 'color_from' => '#D52B1E', 'color_to' => '#FFFFFF',
                'is_egyptian' => false, 'spots_total' => 12, 'spots_left' => 5,
                'departure_dates' => ['2026-06-01','2026-07-15','2026-08-22'],
                'is_active' => true, 'sort_order' => 15,
            ],
            [
                'title'           => ['ar' => 'البانيا — الكنز الخفي',            'en' => 'Albania — The Hidden Gem'],
                'country'         => ['ar' => 'ألبانيا',                          'en' => 'Albania'],
                'desc'            => ['ar' => 'شواطئ البحر الأدرياتيكي والمتوسط بأسعار لا تُصدق وجمال طبيعي بكر لم يكتشفه الكثيرون.', 'en' => 'Adriatic and Mediterranean beaches at unbelievable prices with pristine natural beauty few have discovered.'],
                'highlights'      => ['ar' => ['شاطئ كاميل','جيروكاستر','بحيرة شكودر','ساراندا'], 'en' => ['Ksamil Beach','Gjirokastër','Lake Shkodër','Saranda']],
                'price' => 450, 'currency' => '$', 'duration' => 6,
                'category' => 'beach', 'climate' => 'beach', 'travel_type' => ['friends','solo','couple'],
                'budget_tier' => 'low', 'color_from' => '#E41E20', 'color_to' => '#1A3A5C',
                'is_egyptian' => false, 'spots_total' => 25, 'spots_left' => 18,
                'departure_dates' => ['2026-04-30','2026-05-28','2026-06-25'],
                'is_active' => true, 'sort_order' => 16,
            ],
        ];

        foreach ($trips as $trip) {
            Trip::firstOrCreate(
                ['sort_order' => $trip['sort_order']],
                $trip
            );
        }
    }
}
